language: ruby

cache: bundler

bundler_args: --no-deployment --binstubs=./bin

before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - if [[ ! "${RUBY_VERSION}" =~ "jruby" ]]; then travis_wait 30 rvm rubygems current; fi
  - if [[ ! "${RUBY_VERSION}" =~ "jruby" ]]; then yes | gem update --system --force || true; fi
  - gem --version
  - gem install bundler -v 1.17.3
  - export MY_BUNDLER_VERSION='_1.17.3_'
  - bundle ${MY_BUNDLER_VERSION} --version

install:
  - bundle ${MY_BUNDLER_VERSION} config --local path vendor/bundle
  - bundle ${MY_BUNDLER_VERSION} config --local jobs 3
  - bundle ${MY_BUNDLER_VERSION} config --local retry 3
  - bundle ${MY_BUNDLER_VERSION} config --local binstubs ./bin
  - bundle ${MY_BUNDLER_VERSION} config --local bin ./bin
  - bundle ${MY_BUNDLER_VERSION} install

script:
  - echo $BUNDLE_GEMFILE
  - bundle ${MY_BUNDLER_VERSION} exec rake

gemfile:
  - gemfiles/celluloid_0.16.0.gemfile
  - gemfiles/celluloid_0.17.3.gemfile
  - gemfiles/celluloid_0.17.4.gemfile
  - gemfiles/celluloid_0.18.0.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/celluloid_0.18.0.gemfile
    - rvm: 2.1.3
      gemfile: gemfiles/celluloid_0.18.0.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/celluloid_0.18.0.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/celluloid_0.18.0.gemfile
    - rvm: 2.2.5
      gemfile: gemfiles/celluloid_0.18.0.gemfile
rvm:
  - 2.1.3
  - 2.2.2
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.4.0
  - 2.5.3
  - 2.6.5
  - 2.7.1
  - 3.0.0
  - jruby-19mode
  - jruby-head

env:
  - RACK_ENV=test